[[spring-data-mongodb-reference-documentation]]
= Spring Data MongoDB
:revnumber: {version}
:revdate: {localdate}
:feature-scroll: true

_Spring Data MongoDB provides support for the MongoDB database.
It uses familiar Spring concepts such as a template classes for core API usage and lightweight repository style data access to ease development of applications with a consistent programming model._  +
_Spring Data MongoDB 提供对 MongoDB 数据库的支持。
它采用了一些常见的 Spring 概念，例如用于核心 API 使用的 template 类和轻量级 repository 风格的数据访问，从而通过一致的编程模型简化了应用程序的开发。_

[horizontal]
xref:mongodb.adoc[MongoDB] :: MongoDB support and connectivity  +
MongoDB 支持和连接
xref:repositories.adoc[Repositories] :: Mongo Repositories  +
Mongo Repositories
xref:observability/observability.adoc[Observability] :: Observability Integration  +
可观察性集成
xref:kotlin.adoc[Kotlin] :: Kotlin support
// xref:migration-guides.adoc[Migration] :: Migration Guides
https://github.com/spring-projects/spring-data-commons/wiki[Wiki] :: What's New, Upgrade Notes, Supported Versions, additional cross-version information.  +
新功能、升级说明、支持的版本、额外的跨版本信息

Mark Pollack; Thomas Risberg; Oliver Gierke; Costin Leau; Jon Brisbin; Thomas Darimont; Christoph Strobl; Mark Paluch; Jay Bryant

(C) 2008-{copyright-year} VMware Inc.

Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically.
