[[mongodb.core]]
= MongoDB Support
:page-section-summary-toc: 1

Spring Data support for MongoDB contains a wide range of features:  +
Spring Data 对 MongoDB 的支持包含广泛的功能：

* xref:mongodb/template-config.adoc[Spring configuration support] with Java-based `@Configuration` classes or an XML namespace for a Mongo driver instance and replica sets.  +
在 Spring 中可以使用基于 Java 的 `@Configuration` 类或 XML 命名空间来配置 Mongo driver 实例和副本集。
* xref:mongodb/template-api.adoc[`MongoTemplate` helper class] that increases productivity when performing common Mongo operations.
Includes integrated object mapping between documents and POJOs.  +
`MongoTemplate` 辅助类可提高执行常见 Mongo 操作的效率。它集成了 documents 和 POJO 之间的对象映射功能。
* xref:mongodb/template-api.adoc#mongo-template.exception-translation[Exception translation] into Spring's portable Data Access Exception hierarchy.  +
将异常转换为 Spring 的可移植数据访问异常层次结构。
* Feature-rich xref:mongodb/mapping/mapping.adoc[Object Mapping] integrated with Spring's Conversion Service.  +
功能丰富的对象映射与 Spring 的转换服务集成。
* xref:mongodb/mapping/mapping.adoc#mapping-usage-annotations[Annotation-based mapping metadata] that is extensible to support other metadata formats.  +
基于注释的映射元数据，可扩展以支持其他元数据格式。
* xref:mongodb/lifecycle-events.adoc[Persistence and mapping lifecycle events].  +
持久化和映射生命周期事件。
* xref:mongodb/template-query-operations.adoc[Java-based Query, Criteria, and Update DSLs].  +
基于 Java 的查询、条件和更新 DSL。
* Automatic implementation of xref:repositories.adoc[Repository interfaces], including support for custom query methods.  +
自动实现 Repository 接口，包括对自定义查询方法的支持。
* xref:repositories/core-extensions.adoc#mongodb.repositories.queries.type-safe[QueryDSL integration] to support type-safe queries.  +
集成 QueryDSL 以支持类型安全的查询。
* xref:mongodb/client-session-transactions.adoc[Multi-Document Transactions].  +
多文档事务。
* xref:mongodb/template-query-operations.adoc#mongo.geo-json[GeoSpatial integration].  +
地理空间集成。

For most tasks, you should use `MongoTemplate` or the Repository support, which both leverage the rich mapping functionality.
`MongoTemplate` is the place to look for accessing functionality such as incrementing counters or ad-hoc CRUD operations.
`MongoTemplate` also provides callback methods so that it is easy for you to get the low-level API artifacts, such as `com.mongodb.client.MongoDatabase`, to communicate directly with MongoDB.
The goal with naming conventions on various API artifacts is to copy those in the base MongoDB Java driver so you can easily map your existing knowledge onto the Spring APIs.  +
对于大多数任务，您应该使用 `MongoTemplate` 或 Repository 支持，它们都利用了丰富的映射功能。
`MongoTemplate` 适用于需要访问功能（例如递增计数器或临时 CRUD 操作）时。
`MongoTemplate` 还提供回调方法，以便您轻松获取低级 API 构件（例如 `com.mongodb.client.MongoDatabase`），以便直接与 MongoDB 通信。
各种 API 构件的 命名约定的目标是复制基础 MongoDB Java 驱动程序中的命名约定，以便您可以轻松地将现有知识映射到 Spring API 上。
